version: '3.5'

services:

    nginx:
        container_name: ${NGINX_CONTAINER_NAME:-rgo-apirest-nginx}
        image: ${NGINX_CONTAINER_NAME:-rgo-apirest-nginx}
        build:
            context: ./docker/nginx
            args:
                UID: ${UID:-1000}
                NGINX_VERSION: ${NGINX_VERSION:-1.21}
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
        depends_on:
            - php

    php:
        container_name: ${PHP_CONTAINER_NAME:-rgo-apirest-php}
        image: ${PHP_CONTAINER_NAME:-rgo-apirest-php}
        build:
            context: docker/php
            args:
                UID: ${UID:-1000}
                SYMFONY_VERSION: ${SYMFONY_VERSION:-4.4}
                PHP_VERSION: ${PHP_VERSION:-7.2}
                XDEBUG_ENV: ${XDEBUG_ENV:-production}
        environment:
            XDEBUG_CONFIG: "mode=debug client_host=host.docker.internal client_port=9003 start_with_request=yes"
            PHP_IDE_CONFIG: "serverName=localhost"
        volumes:
            - ./:/var/www
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:delegated